rbac:
  enableKubernetesResourceAccess: true
  extraRules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    verbs:
    - get
    - create
    - update
    - delete
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - create
    - get
    - list
    - watch
    - delete
